config/routes.rb
Rails.application.routes.draw do
  get "/pages/show"
  get "/sign_up", to: "registrations#new"
  post "/users", to: "registrations#create"
  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  delete "/sign_out", to: "sessions#destroy"

  resources :posts do
    resources :comments
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, 
            presence: true, 
            length: { maximum: 250 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, 
            presence: true, 
            length: { minimum: 5, maximum: 100 }
            # uniqueness: { case_sensitive: false }

  validates :body, 
            presence: true, 
            length: { minimum: 30, maximum: 3000 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_secure_password
  has_many :posts
  has_many :comments

  validates :email, 
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 254 },
            format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :username, 
            presence: true,
            uniqueness: true,
            length: { minimum: 6, maximum: 30 }

  validates :password,
            presence: true,
            length: { minimum: 8, maximum: 100 },
            confirmation: true,
            on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_owns_record?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticated
    unless current_user.present?
      flash[:error] = "You must sign in first to perform this action."
      redirect_to sign_in_path
    end
  end

  def user_owns_record?(record)
    current_user == record.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post
  before_action :authenticated

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = "Comment was successfully added!"
      redirect_to @post
    else
      flash.now[:error] = "There was a problem with your comment. Please try again..."
      render "posts/show", status: :unprocessable_entity 
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      flash[:success] = "Comment was successfully deleted!"
      redirect_to @post
    else
      flash.now[:error] = "There was a problem with deleting your comment. Please try again..."
      render "posts/show"
    end
  end

  private

  def get_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, except: [:index, :new, :create]
  before_action :authenticated, except: [:index, :show]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post was successfully published!"
      redirect_to root_path
    else
      flash.now[:error] = "There was a problem with your post. Please try again..."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new(post: @post)
    @comments = @post.comments.includes(:user)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post was successfully updated!"
      redirect_to root_path
    else
      flash.now[:error] = "There was a problem with your post. Please try again..."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = "Post was successfully deleted."
    redirect_to root_path
  end

  private

  def get_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully registered!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = "There was a problem registering you as a user..."
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticated, only: [:destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(user_params[:email].downcase)
    if @user&.authenticate(user_params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Successfully signed in!"
      redirect_to root_path
    else
      flash.now[:error] = "There was a problem signing you in..."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:alert] = "Successfully signed out!"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">

  <div class="comment_content">
    <p class="comment_name">
      Posted by: <%= comment.user.username %>,  <%= time_ago_in_words(comment.created_at) %> ago
    </p>
    <p class="comment_body"><%= comment.body %></p>
  </div>

  <% if current_user && user_owns_record?(comment) %>
    <%= button_to "Delete", 
              post_comment_path(comment.post, comment), 
              method: :delete, 
              data: { turbo_confirm: "Are you sure?" }, 
              class: "button" %>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], local: true) do |f| %>

  <fieldset>
    <%= f.text_area :body, placeholder: "What are you thinking?", maxlength: 250 %>
    <% if @comment.errors[:body].any? %>
      <div class="error-message">
        <%= "#{Comment.human_attribute_name(:body)} #{@comment.errors[:body].first}" %>
      </div>
    <% end %>
  </fieldset>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecreateTumblr</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render "shared/sidebar" %>
  <div id="main_content">
    <%= render "shared/header" %>
    <%= render "shared/flash" %>
    <main>
      <%= yield %>
    </main>
  </div>
</body>
</html>

app/views/pages/show.html.erb
<h1>About</h1>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>

  <fieldset>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, maxlength: 100 %>
      <% if @post.errors[:title].any? %>
        <div class="error-message">
          <%= "#{Post.human_attribute_name(:title)} #{@post.errors[:title].first}" %>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.label :body%>
      <%= f.text_area :body, maxlength: 3000 %>
      <% if @post.errors[:body].any? %>
        <div class="error-message">
          <%= "#{Post.human_attribute_name(:body)} #{@post.errors[:body].first}" %>
        </div>
      <% end %>
    </div>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: "form", locals: {post: @post} %>

app/views/posts/index.html.erb
<section>
  <% @posts.each do |post| %>
    <div class="post_wrapper">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <p class="date"><%= time_ago_in_words(post.created_at) %></p>
      <p class="body">
        <%= truncate(post.body, length: 100, separator: " ", omission: "... (Read more)") %>
      </p>
    </div>
  <% end %>
</section>

app/views/posts/new.html.erb
<%= form_with model: @post, url: posts_url do |f|%>
  <p>
    <%= f.label :title%>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body%>
    <%= f.text_area :body %>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<article>
  <h1 class="title">
    <%= @post.title %>
  </h1>
  <p class="date">
    <%= time_ago_in_words(@post.created_at) %>
  </p>
  <p class="body">
    <%= @post.body %>
  </p>

  <% if current_user && user_owns_record?(@post) %>
    <%= link_to "Edit", edit_post_path(@post), class: "button" %>
    <%= button_to "Delete", 
                post_path(@post), 
                method: :delete, 
                data: { turbo_confirm: "Are you sure?" }, 
                class: "button" %>
  <% end %>
</article>

<section id="comments">
  <% if @comments.present? %>
    <p><%= @comments.count %> comment(s).</p>
    <% @comments.each do |comment| %>
      <%= render "comments/comment", comment: comment %>
    <% end %>
  <% else %>
    <p>No one has commented yet.</p>
  <% end %>
</section>

<%= render "comments/form" %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="flash <%= key %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header id="header">
  <nav>
    <p>Post Feed</p>
    <% if current_user %>
      <%= link_to "Add Post", new_post_path, class: "button" %>
      <%= button_to "Sign Out", 
                      sign_out_path, 
                      method: :delete, 
                      data: { turbo_confirm: "Are you sure?" }, 
                      class: "button" %>
      Signed in as: <%= current_user.username %>
    <% end %>
  </nav>
</header>

app/views/shared/_sidebar.html.erb
<aside id="sidebar">
  <ul>
    <li class="category">
      <%= link_to "Tumblr", root_path %>
    </li>
    <li>
      <%= link_to "All Posts", root_path %>
    </li>
    <li>
      <%= link_to "About Me", pages_show_path %>
    </li>
    <% if !current_user %>
      <li class="sign-in">
        <%= link_to "Sign In", sign_in_path %>
      </li>
    <% end %>
  </ul>
</aside>